### ISSUE TITLE
RFC: Support delegating persistence

### ISSUE THREAD

**Issue by rnixx** [bluedynamics/yafowil#24]
I Have implemented a mechanism to delegate persistence of extracted form data to real world data model via runtime data.

https://github.com/bluedynamics/yafowil/compare/persistence_support

To me this feels like a good compromise between "binding a form lib to a content framework" vs. "no convenience for common persistence tasks" at all.

Comments welcome ;)

**Comment by thet** [comment]
sounds like a nice abstraction! no need to implement the persistence methods in the form class, if there is already a ``writer``, which can be used... e.g. for plone, most of the logic can be defined in ``yafowil.plone``.
cc/ @jensens

**Comment by rnixx** [comment]
for plone i.e. we can introduce a behavior writer which uses the (not yet complete) behavior API:

    from yafowil.base import factory
    from yafowil.plone.form import Form

    def behavior_attr_writer(model, target, value):
        behavior_name, attr_name = target
        behavior = model.behaviors[behavior_name]
        behavior[attr_name] = value

    class MyForm(Form):

        def prepare(self):
            form = factory(
                'form',
                name='myform',
                props={
                    'action': '@@myform',
                    'persist_writer': behavior_attr_writer
                })
            form['title'] = factory(
                'text',
                props={
                    'persist': True,
                    'persist_target': ('basic', 'title')
                })
            form['save'] = factory(
                'submit',
                props={
                    'action': 'save',
                    'expression': True,
                    'handler': self.save,
                }
            self.form = form

        def save(self, widget, data):
            data.write(self.model)

**Comment by rnixx** [comment]
further we should set 'persist' property True by default on single value extracting common blueprints.
Since ``data.write`` must be called explicitly this would not cause any problems

**Comment by jensens** [comment]
:+1:

**Comment by rnixx** [comment]
https://github.com/bluedynamics/yafowil/compare/861e97e925...af07e87679
