### ISSUE TITLE
Yafowil typo in setup.py breaks with setuptools 20.2.2

### ISSUE THREAD

**Issue by do3cc** [bluedynamics/yafowil#26]
The version requirement states
plumber>=1.3,
the newest setuptools stumbles other this
@saily

**Comment by do3cc** [comment]
@jensens I'll happily provide a PR and do a release after lunch.
My username on pypi is do3cc.
But now I have to pick up my kids

**Comment by saily** [comment]
@jensens, @rnixx imho you should cherry-pick this commit and release a `2.1.4` bugfix release
