### ISSUE TITLE
yafowil 2.2 final release

### ISSUE THREAD

**Issue by thet** [bluedynamics/yafowil#28]
Since yafowil.widgets.array and yafowil.widgets.dict have official releases, which depend on yafowil > 2.1.99, yafowil 2.2 needs an official final release to not break peoples installations.
see: https://community.plone.org/t/using-ldap-with-plone-5/1262/29

it looks like, it could be released without regressions - the beta version is in production since quite some time.

/cc @rnixx @jensens

**Comment by rnixx** [comment]
done, yafowil documentation and yafowil demo should also be updated to latest versions.
